### ISSUE TITLE
Damage control tracking issue for UX template semantic change in 1.3

### ISSUE THREAD

**Issue by yupferris** [fusetools/fuselibs-public#537]
In https://github.com/fusetools/uno/pull/1306, we refactored `ux:Template` to generate both a factory class (as it did before) as well as an instance class which, like `ux:Class`, would inherit from the element type the `ux:Template` was declared with. This was done in order to fix scoping issues with template children referencing named objects in their parent scopes (see https://github.com/fusetools/uno/issues/1303), as it allowed us to generate fields on the subclass that would allow it to look up objects in its parent scope correctly (this is how `ux:Class` does this).

While this doesn't seem like a big semantic change at first, it has some unintended consequences that have already been reported by some users with early 1.3 builds. The main issue this causes is that now we can't build templates out of `sealed` classes, eg. `WhileString`. Arguably these classes shouldn't be `sealed` in order to let users subclass them in UX with `ux:Class` for various reasons, but simply removing `sealed` may have some unintended consequences, as it basically expands our public API by making previously inaccessible `internal`/`protected` symbols effectively public via subclassing. Additionally, it's possible that we're doing some type comparisons currently assuming that the instance created from a template factory is of the exact type the template was declared with, which now isn't the case as it could be a subclass.

As it's too late to revert the change for 1.3, we should do a few things right away:
- [ ] Document a workaround for issues that arise. For most issues this is going to be using `ux:Template` with a non-sealed container, eg. `NodeGroup`.
- [ ] Investigate other ways of fixing [the scoping problems](https://github.com/fusetools/uno/issues/1303) than subclassing, to see if we can swap out the original fix with something else for 1.4.

If we're unable to find an alternative fix for the scoping issues, I think we should lean into the change by doing the following:
- [ ] Vetting code for `sealed` classes that shouldn't be `sealed` to allow subclassing/templating. Since we can still mark methods as `sealed`, we should still attempt to hide internal implementation specifics in this way.
- [ ] Documenting (where?) either that 1. generally protected parts of the fuselibs classes shouldn't be overridden unless explicitly stated otherwise, and/or 2. explicitly mark protected parts of fuselibs classes that shouldn't be overridden.
- [ ] Vetting code for type checks/comparisons that assume a template produces a specific type, rather than a type or subtype of the template's declared type.

**Comment by yupferris** [comment]
It looks like we're going to [revert the breaking changes](https://github.com/fusetools/uno/pull/1363) for 1.3 after all, so then the priority here becomes finding an alternative fix for https://github.com/fusetools/uno/issues/1303 only, and the rest of this ticket is invalid. Though between the issues here and https://github.com/fusetools/uno/issues/1358, tests should be added to prevent such breakages in the future.

**Comment by Duckers** [comment]
I'm very opposed to #1363 as the only robust solution here long term is to do the template->class transform.

**Comment by kusma** [comment]
@Duckers: The only long-term robust solution for ux:Class is to no longer generate actual uno classes (to facilitate hot-patching on iOS, for instance), so in the long term these can share the mechanism. In the short term, this fixes real problems.

**Comment by yupferris** [comment]
no longer valid as of https://github.com/fusetools/uno/pull/1364
